Add missing include for ActivityBuffers
Summary:
To fix build error:
```
error C2027: use of undefined type 'libkineto::ActivityBuffers'
```

Signed-off-by: Andre Moreira Magalhaes <andre.magalhaes@collabora.com>